packages:
  - 'packages/*'
  - 'playgrounds/*'

savePrefix: ''

minimumReleaseAge: 1440

catalog:
  typescript: 7.0.2
  tsdown: 0.22.14
  vite: 8.1.5
  vitest: 4.1.10
  '@vitejs/plugin-vue': 6.0.8
  '@vitejs/plugin-vue2': 2.3.4
  vue: 3.5.40
  vue-demi: 0.14.10
  zod: 4.4.3

catalogs:
  vue27:
    vue: 2.7.16

allowBuilds:
  vue-demi: true
  esbuild: true
  core-js: true
  '@parcel/watcher': false

peerDependencyRules:
  allowedVersions:
    vite: '*'
