import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  HOSTS,
  detectEnvironment,
  readVformConfig,
  type LoadedProject,
} from './project'

export type CheckLevel = 'pass' | 'warn' | 'error'

export interface DoctorCheck {
  level: CheckLevel
  message: string
}

export interface DoctorReport {
  ok: boolean
  checks: DoctorCheck[]
}

export function doctorProject(project: LoadedProject): DoctorReport {
  const checks: DoctorCheck[] = []
  const config = readVformConfig(project)
  const environment = detectEnvironment(project)

  if (!config) {
    checks.push({ level: 'error', message: 'Missing .vformjs.json; run vformjs init' })
    return { ok: false, checks }
  }

  const host = HOSTS[config.host]
  checks.push({ level: 'pass', message: `Configured host: ${host.id}` })

  if (project.dependencies[host.uiPackage] == null)
    checks.push({ level: 'error', message: `Missing UI dependency ${host.uiPackage}` })
  else
    checks.push({ level: 'pass', message: `Found UI dependency ${host.uiPackage}` })

  if (project.dependencies[host.adapterPackage] == null) {
    checks.push({
      level: 'error',
      message: `Missing adapter ${host.adapterPackage}; install ${host.adapterPackage} ${host.uiPackage}`,
    })
  }
  else {
    checks.push({ level: 'pass', message: `Found adapter ${host.adapterPackage}` })
  }

  if (environment.vueMajor != null && environment.vueMajor !== host.vueMajor) {
    checks.push({
      level: 'error',
      message: `${host.id} expects Vue ${host.vueMajor}, found Vue ${environment.vueMajor}`,
    })
  }
  else if (environment.vueMajor != null) {
    checks.push({ level: 'pass', message: `Vue ${environment.vueMajor} matches ${host.id}` })
  }
  else {
    checks.push({ level: 'warn', message: 'Could not determine the Vue major version' })
  }

  if (config.zod && !environment.zod)
    checks.push({ level: 'error', message: 'Config enables Zod but dependency zod is missing' })
  else if (config.zod)
    checks.push({ level: 'pass', message: 'Zod dependency found' })

  if (environment.hosts.length > 1) {
    checks.push({
      level: 'warn',
      message: `Multiple UI hosts installed (${environment.hosts.join(', ')}); using configured ${config.host}`,
    })
  }

  const sourceRoot = resolve(project.root, config.sourceDir)
  if (!existsSync(sourceRoot)) {
    checks.push({ level: 'error', message: `Missing generated source directory ${config.sourceDir}` })
  }
  else {
    const generated = readdirSync(sourceRoot, { withFileTypes: true })
      .filter(entry => entry.isFile() && entry.name.endsWith('.ts'))
      .map(entry => resolve(sourceRoot, entry.name))
      .filter(path => readFileSync(path, 'utf8').includes('Generated by vformjs'))
    if (!generated.length) {
      checks.push({ level: 'error', message: `No generated forms found in ${config.sourceDir}` })
    }
    else {
      const invalid = generated.filter(path => !readFileSync(path, 'utf8').includes(host.adapterPackage))
      if (invalid.length)
        checks.push({ level: 'error', message: `${invalid.length} generated form(s) import a different host adapter` })
      else
        checks.push({ level: 'pass', message: `${generated.length} generated form(s) use ${host.adapterPackage}` })
    }
  }

  return {
    ok: !checks.some(check => check.level === 'error'),
    checks,
  }
}
