import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import {
  CONFIG_FILE,
  HOSTS,
  detectEnvironment,
  isHostId,
  readVformConfig,
  type HostId,
  type LoadedProject,
  type VformConfig,
} from './project'

export type FileAction = 'create' | 'update' | 'unchanged' | 'would-create' | 'would-update'

export interface FileOperation {
  action: FileAction
  path: string
}

export interface WriteOptions {
  dryRun?: boolean
  force?: boolean
}

interface FilePlan {
  absolutePath: string
  content: string
  action: FileAction
}

export interface ScaffoldOptions extends WriteOptions {
  host?: string
  name?: string
  sourceDir?: string
  zod?: boolean
}

export function planFiles(
  project: LoadedProject,
  files: ReadonlyArray<{ path: string, content: string }>,
  options: WriteOptions = {},
): { plans: FilePlan[], operations: FileOperation[] } {
  const plans = files.map(({ path, content }) => {
    const absolutePath = resolve(project.root, path)
    if (!absolutePath.startsWith(`${project.root}/`) && absolutePath !== project.root)
      throw new Error(`Refusing to write outside the project: ${path}`)
    const exists = existsSync(absolutePath)
    if (exists) {
      const previous = readFileSync(absolutePath, 'utf8')
      if (previous === content)
        return { absolutePath, content, action: 'unchanged' as const }
      if (!options.force)
        throw new Error(`${relative(project.root, absolutePath)} already exists with different content; rerun with --force to replace it`)
      return {
        absolutePath,
        content,
        action: options.dryRun ? 'would-update' as const : 'update' as const,
      }
    }
    return {
      absolutePath,
      content,
      action: options.dryRun ? 'would-create' as const : 'create' as const,
    }
  })

  return {
    plans,
    operations: plans.map(plan => ({
      action: plan.action,
      path: relative(project.root, plan.absolutePath),
    })),
  }
}

export function commitPlans(plans: ReadonlyArray<FilePlan>, dryRun = false): void {
  if (dryRun)
    return
  for (const plan of plans) {
    if (plan.action === 'unchanged')
      continue
    mkdirSync(dirname(plan.absolutePath), { recursive: true })
    writeFileSync(plan.absolutePath, plan.content)
  }
}

function formName(raw: string): { kebab: string, pascal: string, camel: string } {
  if (!/^[a-z][a-z0-9-]*$/.test(raw))
    throw new Error(`Form name must be kebab-case: ${raw}`)
  const words = raw.split('-')
  const pascal = words.map(word => `${word[0]!.toUpperCase()}${word.slice(1)}`).join('')
  return { kebab: raw, pascal, camel: `${pascal[0]!.toLowerCase()}${pascal.slice(1)}` }
}

function selectConfig(project: LoadedProject, options: ScaffoldOptions): VformConfig {
  const current = readVformConfig(project)
  const detected = detectEnvironment(project)
  let host: HostId | undefined

  if (options.host != null) {
    if (!isHostId(options.host))
      throw new Error(`Unsupported host ${options.host}; choose ${Object.keys(HOSTS).join(', ')}`)
    host = options.host
  }
  else if (current) {
    host = current.host
  }
  else if (detected.hosts.length === 1) {
    host = detected.hosts[0]
  }
  else if (detected.hosts.length > 1) {
    throw new Error(`Multiple UI hosts detected (${detected.hosts.join(', ')}); pass --host explicitly`)
  }

  if (!host)
    throw new Error(`No supported UI host detected; pass --host ${Object.keys(HOSTS).join('|')}`)

  return {
    version: 1,
    host,
    zod: options.zod ?? current?.zod ?? detected.zod,
    sourceDir: options.sourceDir ?? current?.sourceDir ?? 'src/forms',
  }
}

export function renderForm(config: VformConfig, rawName: string): string {
  const name = formName(rawName)
  const host = HOSTS[config.host]
  const submitType = `(values: ${name.pascal}FormValues) => void | Promise<void>`

  if (config.zod) {
    return `/** Generated by vformjs. Safe to edit after creation. */\nimport { useZodForm } from '${host.adapterPackage}/zod'\nimport { z } from 'zod'\n\nexport const ${name.camel}FormSchema = z.object({\n  name: z.string().min(1, 'Name is required'),\n  email: z.email('Enter a valid email'),\n})\n\nexport type ${name.pascal}FormValues = z.output<typeof ${name.camel}FormSchema>\nexport type ${name.pascal}FormSubmit = ${submitType}\n\nexport function use${name.pascal}Form(onSubmit: ${name.pascal}FormSubmit) {\n  return useZodForm({\n    schema: ${name.camel}FormSchema,\n    defaults: { name: '', email: '' },\n    onSubmit,\n  })\n}\n`
  }

  return `/** Generated by vformjs. Safe to edit after creation. */\nimport { r, ${host.formFactory} } from '${host.adapterPackage}'\n\nexport interface ${name.pascal}FormValues {\n  name: string\n  email: string\n}\n\nexport type ${name.pascal}FormSubmit = ${submitType}\n\nexport function use${name.pascal}Form(onSubmit: ${name.pascal}FormSubmit) {\n  return ${host.formFactory}({\n    defaults: { name: '', email: '' },\n    rules: {\n      name: [r.required('Name is required')],\n      email: [r.required('Email is required'), r.email('Enter a valid email')],\n    },\n    onSubmit,\n  })\n}\n`
}

export function initProject(project: LoadedProject, options: ScaffoldOptions = {}): FileOperation[] {
  const config = selectConfig(project, options)
  const name = options.name ?? 'example'
  const files = [
    { path: CONFIG_FILE, content: `${JSON.stringify(config, null, 2)}\n` },
    { path: `${config.sourceDir}/use-${formName(name).kebab}-form.ts`, content: renderForm(config, name) },
  ]
  const { plans, operations } = planFiles(project, files, options)
  commitPlans(plans, options.dryRun)
  return operations
}

export function addForm(project: LoadedProject, options: ScaffoldOptions = {}): FileOperation[] {
  const config = readVformConfig(project)
  if (!config)
    throw new Error(`Run vformjs init before adding a form`)
  const name = options.name
  if (!name)
    throw new Error(`vformjs add form requires a name`)
  const files = [{
    path: `${config.sourceDir}/use-${formName(name).kebab}-form.ts`,
    content: renderForm(config, name),
  }]
  const { plans, operations } = planFiles(project, files, options)
  commitPlans(plans, options.dryRun)
  return operations
}
